In [1]:
import numpy as np

In [2]:
# creating an array with numpy

arr = np.array([1,2,3,4,5])

In [3]:
print(arr)

[1 2 3 4 5]


In [4]:
print(np.__version__)

1.18.5


Creating a nd array

In [5]:
print(type(arr))

<class 'numpy.ndarray'>


# Creating a 2-D array

In [7]:
two_d_arr = np.array([[1,2,3],[4,5,6]])

In [8]:
print(two_d_arr)

[[1 2 3]
 [4 5 6]]
